import Link from "next/link";
import { CalendarDays,ExternalLink,FileCheck2,Target,UserRound } from "lucide-react";
import { PJ_LABEL,STATUS_PROGRESS } from "@/lib/constants";
import { averageProgress,formatDate } from "@/lib/utils";
import type { BeritaAcaraData } from "@/types";
import { DeadlineBadge,StatusBadge } from "@/components/status-badge";
export function DetailView({item,privateView=false,admin=false}:{item:BeritaAcaraData;privateView?:boolean;admin?:boolean}) {
 const progress=averageProgress(item.poinRencana);
 return <div className="detail-grid"><main><section className="card p-6"><div className="flex flex-wrap items-center gap-2"><span className="eyebrow">{item.nomor}</span></div><h1 className="mt-3 text-3xl font-black">{item.nama}</h1><p className="muted leading-relaxed">{item.deskripsi||"Tidak ada ringkasan tambahan."}</p><div className="flex flex-wrap gap-5 text-sm"><span className="flex items-center gap-2"><CalendarDays size={17}/>{formatDate(item.tanggal)}</span><span>{item.poinRencana.length} poin rencana</span></div></section>
  <div className="mt-5 point-list">{item.poinRencana.map((point,index)=><article className="card point" key={point.id}><div className="flex items-start justify-between gap-4"><div><span className="eyebrow">Poin {index+1}</span><h3 className="mt-2 text-lg leading-snug">{point.detailPoin}</h3></div>{admin&&<Link className="btn btn-secondary shrink-0" href={"/admin/poin/"+point.id+"/edit"}>Edit</Link>}</div><div className="flex flex-wrap gap-2"><StatusBadge status={point.status}/><DeadlineBadge point={point}/></div><div className="mt-3 progress"><span style={{width:STATUS_PROGRESS[point.status]+"%"}}/></div><div className="point-meta"><div><span className="label flex items-center gap-2"><Target size={15}/>Target pelaksanaan</span><strong>{formatDate(point.targetPelaksanaan)}</strong></div><div><span className="label flex items-center gap-2"><UserRound size={15}/>Penanggung jawab</span><strong className="text-sm">{PJ_LABEL[point.penanggungJawab]}</strong></div><div className="span-2"><span className="label flex items-center gap-2"><FileCheck2 size={15}/>Indikator output</span><p>{point.indikatorOutput}</p></div>{privateView&&<><div className="span-2 rounded-xl bg-gray-50 p-4"><span className="label">Catatan internal</span><p className="mb-0">{point.catatan||"Tidak ada catatan."}</p></div><div className="span-2"><span className="label">Evidence ({point.evidence?.length||0})</span>{point.evidence?.length?<div className="grid gap-2">{point.evidence.map(ev=><a key={ev.id} className="flex items-center justify-between rounded-xl border border-gray-200 p-3 text-sm font-bold hover:border-red-300" target="_blank" rel="noreferrer" href={ev.evidenceUrl}>{ev.judul}<ExternalLink size={15}/></a>)}</div>:<p className="muted text-sm">Belum ada evidence.</p>}</div></>}</div></article>)}</div>
 </main><aside><section className="card p-5"><span className="eyebrow">Ringkasan progres</span><div className="my-3 text-5xl font-black">{progress}%</div><div className="progress"><span style={{width:progress+"%"}}/></div><p className="muted mt-4 text-sm">Rata-rata dihitung dari bobot status seluruh poin.</p>{privateView&&item.dokumenUrl&&<a className="btn btn-primary mt-3 w-full" href={item.dokumenUrl} target="_blank" rel="noreferrer">Buka dokumen <ExternalLink size={16}/></a>}{admin&&<><Link className="btn btn-secondary mt-2 w-full" href={"/admin/berita-acara/"+item.id+"/edit"}>Edit berita acara</Link><Link className="btn btn-secondary mt-2 w-full" href={"/admin/berita-acara/"+item.id+"/poin/create"}>Tambah poin</Link></>}</section>{!privateView&&<div className="notice mt-4">Dokumen, evidence, dan catatan hanya tersedia bagi pengguna internal yang berwenang.</div>}</aside></div>
}
