"use client";
import { useMemo,useState } from "react";
import Link from "next/link";
import { BarChart3,CheckCircle2,Clock3,FileText,Search,XCircle } from "lucide-react";
import { BULAN,PJ_LABEL,STATUS_LABEL } from "@/lib/constants";
import { averageProgress,dashboardStats,formatDate,overallStatus } from "@/lib/utils";
import type { BeritaAcaraData,PenanggungJawab,StatusPoin } from "@/types";
import { MonitoringCharts } from "@/components/monitoring-charts";
import { StatusBadge } from "@/components/status-badge";
const statMeta=[["totalBerita","Berita Acara Terupload",FileText,"#c71920"],["totalPoin","Total Poin",BarChart3,"#2563eb"],["progress","Progress Rata-rata",Clock3,"#7c3aed"],["selesai","Sudah Dilaksanakan",CheckCircle2,"#16a34a"],["proses","Dalam Proses",Clock3,"#f59e0b"],["belum","Belum Dilaksanakan",XCircle,"#dc2626"]] as const;
export function PublicDashboard({items,basePath="/berita-acara",compact=false}:{items:BeritaAcaraData[];basePath?:string;compact?:boolean}) {
 const [query,setQuery]=useState("");const [month,setMonth]=useState("");const [year,setYear]=useState("");const [status,setStatus]=useState("");const [pj,setPj]=useState("");const [sort,setSort]=useState("newest");const [page,setPage]=useState(1);const years=[...new Set(items.map(x=>x.tahun))].sort((a,b)=>b-a);
 const filtered=useMemo(()=>items.filter(x=>(!query||(x.nama+" "+x.nomor).toLowerCase().includes(query.toLowerCase()))&&(!month||x.bulan===Number(month))&&(!year||x.tahun===Number(year))&&(!status||x.poinRencana.some(p=>p.status===status as StatusPoin))&&(!pj||x.poinRencana.some(p=>p.penanggungJawab===pj as PenanggungJawab))).sort((a,b)=>sort==="oldest"?a.tanggal.localeCompare(b.tanggal):sort==="progress"?averageProgress(b.poinRencana)-averageProgress(a.poinRencana):b.tanggal.localeCompare(a.tanggal)),[items,query,month,year,status,pj,sort]);
 const stats=dashboardStats(filtered);const paged=filtered.slice((page-1)*6,page*6);const pages=Math.max(1,Math.ceil(filtered.length/6));const reset=()=>{setQuery("");setMonth("");setYear("");setStatus("");setPj("");setSort("newest");setPage(1)};
 return <div>{!compact&&<><div className="grid-stats">{statMeta.map(([key,label,Icon,color])=><article className="card stat" key={key}><div className="mb-3 flex items-center justify-between"><span className="stat-label">{label}</span><Icon size={20} color={color}/></div><div className="stat-value">{stats[key]}{key==="progress"?"%":""}</div></article>)}</div><div className="mt-5"><MonitoringCharts items={filtered}/></div></>}
  <section className="card mt-5" style={{padding:20}}><div className="mb-4"><h2 className="text-xl font-extrabold">Daftar Berita Acara</h2><p className="muted text-sm">Telusuri hasil pleno dan perkembangan setiap tindak lanjut.</p></div><div className="filter-grid mb-5"><label className="relative"><Search size={17} className="absolute left-3 top-3.5 text-gray-400"/><input className="input pl-10" value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Cari nama atau nomor..."/></label><select className="input" value={month} onChange={e=>{setMonth(e.target.value);setPage(1)}}><option value="">Semua bulan</option>{BULAN.map((x,i)=><option value={i+1} key={x}>{x}</option>)}</select><select className="input" value={year} onChange={e=>{setYear(e.target.value);setPage(1)}}><option value="">Semua tahun</option>{years.map(x=><option key={x}>{x}</option>)}</select><select className="input" value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}}><option value="">Semua status</option>{Object.entries(STATUS_LABEL).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select><select className="input" value={pj} onChange={e=>{setPj(e.target.value);setPage(1)}}><option value="">Semua penanggung jawab</option>{Object.entries(PJ_LABEL).map(([k,v])=><option value={k} key={k}>{v.replace("Subbagian ","")}</option>)}</select><select className="input" value={sort} onChange={e=>setSort(e.target.value)}><option value="newest">Terbaru</option><option value="oldest">Terlama</option><option value="progress">Progress tertinggi</option></select><button className="btn btn-secondary" onClick={reset}>Reset</button></div>
   {paged.length?<><div className="table-wrap"><table className="table"><thead><tr><th>Berita Acara</th><th>Tanggal</th><th>Poin</th><th>Progress</th><th>Status</th><th></th></tr></thead><tbody>{paged.map(x=>{const p=averageProgress(x.poinRencana);return <tr key={x.id}><td><strong className="block">{x.nama}</strong><span className="muted text-xs">{x.nomor}</span></td><td>{formatDate(x.tanggal)}</td><td>{x.poinRencana.length}</td><td><div className="mb-1 font-bold">{p}%</div><div className="progress w-28"><span style={{width:p+"%"}}/></div></td><td><StatusBadge status={overallStatus(x.poinRencana)}/></td><td><Link className="font-bold text-red-700" href={basePath+"/"+x.id}>Lihat detail →</Link></td></tr>})}</tbody></table></div><div className="mobile-cards">{paged.map(x=><article className="card p-4" key={x.id}><span className="muted text-xs">{x.nomor}</span><h3 className="mt-2 text-base">{x.nama}</h3><div className="mb-4 flex items-center justify-between text-sm"><span>{formatDate(x.tanggal)}</span><StatusBadge status={overallStatus(x.poinRencana)}/></div><Link className="btn btn-secondary w-full" href={basePath+"/"+x.id}>Lihat detail</Link></article>)}</div><div className="mt-5 flex items-center justify-between text-sm"><span className="muted">{filtered.length} data ditemukan</span><div className="flex gap-2"><button disabled={page===1} className="btn btn-secondary disabled:opacity-40" onClick={()=>setPage(p=>p-1)}>Sebelumnya</button><span className="px-2 py-2">{page}/{pages}</span><button disabled={page===pages} className="btn btn-secondary disabled:opacity-40" onClick={()=>setPage(p=>p+1)}>Berikutnya</button></div></div></>:<div className="empty">Tidak ada berita acara yang sesuai dengan filter.</div>}</section></div>
}
