"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { BULAN,PJ_LABEL,STATUS_LABEL } from "@/lib/constants";
import type { BeritaAcaraData,PoinData } from "@/types";
type BAProps={initial?:BeritaAcaraData};
export function BeritaForm({initial}:BAProps){const router=useRouter();const [tanggal,setTanggal]=useState(initial?.tanggal.slice(0,10)||"");const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const data=Object.fromEntries(new FormData(e.currentTarget));const url=initial?"/api/berita-acara/"+initial.id:"/api/berita-acara";const r=await fetch(url,{method:initial?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const b=await r.json();if(!r.ok){setMessage(b.message||"Data gagal disimpan");setBusy(false);return}router.push("/admin/berita-acara/"+b.id);router.refresh()}
 return <form className="card form-card" onSubmit={submit}>{message&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{message}</div>}<div className="form-grid"><Field label="Nomor Berita Acara"><input className="input" name="nomor" defaultValue={initial?.nomor} required/></Field><Field label="Tanggal Berita Acara"><input className="input" type="date" name="tanggal" value={tanggal} onChange={e=>setTanggal(e.target.value)} required/></Field><Field label="Bulan"><input className="input" name="bulan" readOnly value={tanggal?BULAN[Number(tanggal.slice(5,7))-1]||"":""}/></Field><Field label="Tahun"><input className="input" name="tahun" readOnly value={tanggal?tanggal.slice(0,4):""}/></Field><Field label="Nama Berita Acara" span><input className="input" name="nama" defaultValue={initial?.nama} required/></Field><Field label="Link URL Dokumen" span><input className="input" type="url" name="dokumenUrl" defaultValue={initial?.dokumenUrl} required placeholder="https://..."/></Field><Field label="Deskripsi / ringkasan" span><textarea className="input min-h-28" name="deskripsi" defaultValue={initial?.deskripsi||""}/></Field></div><div className="mt-6 flex gap-3"><button disabled={busy} className="btn btn-primary">{busy?"Menyimpan...":"Simpan berita acara"}</button><button type="button" className="btn btn-secondary" onClick={()=>router.back()}>Batal</button></div></form>}
export function PoinForm({beritaAcaraId,initial}:{beritaAcaraId:string;initial?:PoinData}){const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");const data=Object.fromEntries(new FormData(e.currentTarget));const url=initial?"/api/poin/"+initial.id:"/api/berita-acara/"+beritaAcaraId+"/poin";const r=await fetch(url,{method:initial?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const b=await r.json();if(!r.ok){setMessage(b.message||"Poin gagal disimpan");setBusy(false);return}router.push("/admin/berita-acara/"+beritaAcaraId);router.refresh()}
 return <form className="card form-card" onSubmit={submit}>{message&&<div className="mb-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{message}</div>}<div className="form-grid"><Field label="Detail poin rencana" span><textarea className="input min-h-28" name="detailPoin" defaultValue={initial?.detailPoin} required/></Field><Field label="Target pelaksanaan"><input className="input" type="date" name="targetPelaksanaan" defaultValue={initial?.targetPelaksanaan.slice(0,10)} required/></Field><Field label="Status / progres"><select className="input" name="status" defaultValue={initial?.status||"BELUM_DILAKSANAKAN"}>{Object.entries(STATUS_LABEL).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></Field><Field label="Penanggung jawab" span><select className="input" name="penanggungJawab" defaultValue={initial?.penanggungJawab||"KEUANGAN_UMUM_LOGISTIK"}>{Object.entries(PJ_LABEL).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></Field><Field label="Indikator output" span><textarea className="input" name="indikatorOutput" defaultValue={initial?.indikatorOutput} required/></Field><Field label="Catatan internal" span><textarea className="input min-h-24" name="catatan" defaultValue={initial?.catatan||""}/></Field></div><div className="mt-6 flex gap-3"><button disabled={busy} className="btn btn-primary">{busy?"Menyimpan...":"Simpan poin"}</button><button type="button" className="btn btn-secondary" onClick={()=>router.back()}>Batal</button></div></form>}
function Field({label,span,children}:{label:string;span?:boolean;children:React.ReactNode}){return <label className={span?"span-2":""}><span className="label">{label}</span>{children}</label>}
